apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

dashboards:
  - name: 'Stock App Dashboard'
    folder: 'HAY2010'
    type: file
    options:
      path: /var/lib/grafana/dashboards
