apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - configmap.yaml
  - secrets.yaml

commonLabels:
  app.kubernetes.io/name: stock-app
  app.kubernetes.io/part-of: hay2010
  app.kubernetes.io/managed-by: kustomize
